export const prizelist = [
    ["Hunter Charm", "Training / Grinding", "Casino Prize Shop", "3,500,000", "Casino Tokens"],
    ["Rare Charm", "Training / Grinding", "Casino Prize Shop", "2,500,000", "Casino Tokens"],
    ["Greed Charm", "Training / Grinding", "Casino Prize Shop", "2,500,000", "Casino Tokens"],
    ["Greninja-Bond", "Pokemon", "Casino Prize Shop", "250,000", "Casino Tokens"],
    ["Beldum", "Pokemon", "Casino Prize Shop", "150,000", "Casino Tokens"],
    ["Master Ball", "Pokeball", "Casino Prize Shop", "125,000", "Casino Tokens"],
    ["Galladite", "Evolution / Form", "Casino Prize Shop", "100,000", "Casino Tokens"],
    ["Sablenite", "Evolution / Form", "Casino Prize Shop", "100,000", "Casino Tokens"],
    ["Larionite", "Evolution / Form", "Casino Prize Shop", "100,000", "Casino Tokens"],
    ["Focus Sash (Permanent)", "Battle", "Casino Prize Shop", "50,000", "Casino Tokens"],
    ["Gardevoir Mount", "Decoration / Mount", "Casino Prize Shop", "50,000", "Casino Tokens"],
    ["Slakoth", "Pokemon", "Casino Prize Shop", "40,000", "Casino Tokens"],
    ["Macho Brace", "Training / Grinding", "Casino Prize Shop", "40,000", "Casino Tokens"],
    ["IV Gem", "Training / Grinding", "Casino Prize Shop", "32,500", "Casino Tokens"],
    ["Riolu", "Pokemon", "Casino Prize Shop", "30,000", "Casino Tokens"],
    ["Expert Belt", "Battle", "Casino Prize Shop", "30,000", "Casino Tokens"],
    ["Master Cape", "Decoration / Mount", "Casino Prize Shop", "30,000", "Casino Tokens"],
    ["Ancient Key (Tooth Half)", "Key Item", "Casino Prize Shop", "30,000", "Casino Tokens"],
    ["Choice Band", "Battle", "Casino Prize Shop", "25,000", "Casino Tokens"],
    ["Choice Scarf", "Battle", "Casino Prize Shop", "25,000", "Casino Tokens"],
    ["Choice Specs", "Battle", "Casino Prize Shop", "25,000", "Casino Tokens"],
    ["Budew", "Pokemon", "Casino Prize Shop", "20,000", "Casino Tokens"],
    ["TM10 - Hidden Power", "TM / HM", "Casino Prize Shop", "20,000", "Casino Tokens"],
    ["Effort Brace", "Training / Grinding", "Casino Prize Shop", "20,000", "Casino Tokens"],
    ["Dubious Disc", "Evolution / Form", "Casino Prize Shop", "17,500", "Casino Tokens"],
    ["Up-Grade", "Evolution / Form", "Casino Prize Shop", "10,000", "Casino Tokens"],
    ["Shuckle", "Pokemon", "Casino Prize Shop", "10,000", "Casino Tokens"],
    ["HM - Defog", "TM / HM", "Casino Prize Shop", "7,500", "Casino Tokens"],
    ["IV Deductor", "Training / Grinding", "Casino Prize Shop", "7,500", "Casino Tokens"],
    ["HM - Waterfall", "TM / HM", "Casino Prize Shop", "5,000", "Casino Tokens"],
    ["Drop Rate Blessing", "Key Item", "Casino Prize Shop", "5,000", "Casino Tokens"],
    ["HM - Dive", "TM / HM", "Casino Prize Shop", "5,000", "Casino Tokens"],
    ["Ralts", "Pokemon", "Casino Prize Shop", "4,000", "Casino Tokens"],
    ["Sableye", "Pokemon", "Casino Prize Shop", "3,500", "Casino Tokens"],
    ["Moss Rock", "Evolution / Form", "Casino Prize Shop", "1,000", "Casino Tokens"],
    ["Ice Rock", "Evolution / Form", "Casino Prize Shop", "1,000", "Casino Tokens"],
    ["Scope Lens", "Battle", "Casino Prize Shop", "1,000", "Casino Tokens"],
    ["Wide Lens", "Battle", "Casino Prize Shop", "1,000", "Casino Tokens"],
    ["Focus Sash", "Battle", "Casino Prize Shop", "500", "Casino Tokens"],
    ["Keldeo", "Pokemon", "Clan Wars Prize Shop", "5,500", "Clan Wars Token"],
    ["Landorus", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Tornadus", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Thundurus", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Tapu Lele", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Tape Koko", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Tapu Bulu", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Tapu Fini", "Pokemon", "Clan Wars Prize Shop", "4,000", "Clan Wars Token"],
    ["Tornadus Mount", "Decoration / Mount", "Clan Wars Prize Shop", "3,000", "Clan Wars Token"],
    ["Azelf", "Pokemon", "Clan Wars Prize Shop", "2,500", "Clan Wars Token"],
    ["Latias", "Pokemon", "Clan Wars Prize Shop", "2,500", "Clan Wars Token"],
    ["Latios", "Pokemon", "Clan Wars Prize Shop", "2,500", "Clan Wars Token"],
    ["Kyurem", "Pokemon", "Clan Wars Prize Shop", "2,500", "Clan Wars Token"],
    ["Lopunnite", "Evolution / Form", "Clan Wars Prize Shop", "1,500", "Clan Wars Token"],
    ["Latiasite", "Evolution / Form", "Clan Wars Prize Shop", "1,500", "Clan Wars Token"],
    ["Latiosite", "Evolution / Form", "Clan Wars Prize Shop", "1,500", "Clan Wars Token"],
    ["Larvitar", "Pokemon", "Clan Wars Prize Shop", "1,250", "Clan Wars Token"],
    ["Life Orb", "Battle", "Clan Wars Prize Shop", "800", "Clan Wars Token"],
    ["Assault Vest", "Battle", "Clan Wars Prize Shop", "750", "Clan Wars Token"],
    ["Eviolite", "Battle", "Clan Wars Prize Shop", "750", "Clan Wars Token"],
    ["Ancient Key (Loop Half)", "Key Item", "Clan Wars Prize Shop", "700", "Clan Wars Token"],
    ["Cameruptite", "Evolution / Form", "Clan Wars Prize Shop", "600", "Clan Wars Token"],
    ["Soul Dew", "Battle", "Clan Wars Prize Shop", "500", "Clan Wars Token"],
    ["Leftovers", "Battle", "Clan Wars Prize Shop", "300", "Clan Wars Token"],
    ["Metronome", "Battle", "Clan Wars Prize Shop", "50", "Clan Wars Token"],
    ["Tutor Move Ticket", "Training / Grinding", "Clan Wars Prize Shop", "50", "Clan Wars Token"],
    ["Egg Move Ticket", "Training / Grinding", "Clan Wars Prize Shop", "50", "Clan Wars Token"],
    ["Binding Band", "Battle", "Clan Wars Prize Shop", "20", "Clan Wars Token"],
    ["Jirachi", "Pokemon", "Philanthropist Prize Shop", "200,000", "Philanthropist Point"],
    ["Marshadow", "Pokemon", "Philanthropist Prize Shop", "200,000", "Philanthropist Point"],
    ["Crown", "Decoration / Mount", "Philanthropist Prize Shop", "100,000", "Philanthropist Point"],
    ["Gold Cape", "Decoration / Mount", "Philanthropist Prize Shop", "100,000", "Philanthropist Point"],
    ["Money Glasses", "Decoration / Mount", "Philanthropist Prize Shop", "100,000", "Philanthropist Point"],
    ["Metagrossite", "Evolution / Form", "Philanthropist Prize Shop", "50,000", "Philanthropist Point"],
    ["Steelixite", "Evolution / Form", "Philanthropist Prize Shop", "35,000", "Philanthropist Point"],
    ["Amie Stone", "Evolution / Form", "Philanthropist Prize Shop", "30,000", "Philanthropist Point"],
    ["Ancient Kay (tooth Half)", "Key Item", "Philanthropist Prize Shop", "15,000", "Philanthropist Point"],
    ["Halo", "Decoration / Mount", "Philanthropist Prize Shop", "10,000", "Philanthropist Point"],
    ["Type: Null", "Pokemon", "Philanthropist Prize Shop", "10,000", "Philanthropist Point"],
    ["Angel Wings", "Decoration / Mount", "Philanthropist Prize Shop", "7,500", "Philanthropist Point"],
    ["Choice Band", "Battle", "Philanthropist Prize Shop", "6,000", "Philanthropist Point"],
    ["Choice Scarf", "Battle", "Philanthropist Prize Shop", "6,000", "Philanthropist Point"],
    ["Choice Specs", "Battle", "Philanthropist Prize Shop", "6,000", "Philanthropist Point"],
    ["Bug Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Dark Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Dragon Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Electric Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Fairy Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Fighting Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Fire Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Flying Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Ghost Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Grass Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Ground Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Poison Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Psychic Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Rock Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Poison Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Psychic Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Rock Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Steel Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Water Memory", "Evolution / Form", "Philanthropist Prize Shop", "1,000", "Philanthropist Point"],
    ["Necrozma", "Pokemon", "Elite Prize Shop", "450", "Elite Tokens"],
    ["Zeraora", "Pokemon", "Elite Prize Shop", "300", "Elite Tokens"],
    ["Virizion", "Pokemon", "Elite Prize Shop", "150", "Elite Tokens"],
    ["Old Sea Map", "Key Item", "Elite Prize Shop", "125", "Elite Tokens"],
    ["Banettite", "Evolution / Form", "Elite Prize Shop", "75", "Elite Tokens"],
    ["Glalitite", "Evolution / Form", "Elite Prize Shop", "75", "Elite Tokens"],
    ["Abomasite", "Evolution / Form", "Elite Prize Shop", "75", "Elite Tokens"],
    ["Heracronite", "Evolution / Form", "Elite Prize Shop", "75", "Elite Tokens"],
    ["Gengarite", "Evolution / Form", "Elite Prize Shop", "75", "Elite Tokens"],
    ["Aggronite", "Evolution / Form", "Elite Prize Shop", "75", "Elite Tokens"],
    ["AFK Rod", "Key Item", "Elite Prize Shop", "50", "Elite Tokens"],
    ["Shiny Charm", "Training / Grinding", "Elite Prize Shop", "30", "Elite Tokens"],
    ["Exp Share (Enhanced)", "Training / Grinding", "Elite Prize Shop", "20", "Elite Tokens"],
    ["Smoke Ball", "Training / Grinding", "Elite Prize Shop", "20", "Elite Tokens"],
    ["Transfer Move Ticket", "Training / Grinding", "Elite Prize Shop", "15", "Elite Tokens"],
    ["Cleanse Tag", "Battle", "Elite Prize Shop", "10", "Elite Tokens"],
    ["Treasure Key", "Key Item", "Elite Prize Shop", "1", "Elite Tokens"],
    ["Deoxys", "Pokemon", "PVP Prize Shop", "7,000", "PVP Tokens"],
    ["Landorus", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Tornadus", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Thundurus", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Tapu Lele", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Tapu Koko", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Tapu Bulu", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Tapu Fini", "Pokemon", "PVP Prize Shop", "5,000", "PVP Tokens"],
    ["Cobalion", "Pokemon", "PVP Prize Shop", "3,500", "PVP Tokens"],
    ["Landorus Mount", "Decoration / Mount", "PVP Prize Shop", "3,000", "PVP Tokens"],
    ["Kangaskhanite", "Evolution / Form", "PVP Prize Shop", "1,500", "PVP Tokens"],
    ["Scizorite", "Evolution / Form", "PVP Prize Shop", "1,500", "PVP Tokens"],
    ["Honedge", "Pokemon", "PVP Prize Shop", "1,250", "PVP Tokens"],
    ["Axew", "Pokemon", "PVP Prize Shop", "1,000", "PVP Tokens"],
    ["Toxic Orb", "Battle", "PVP Prize Shop", "800", "PVP Tokens"],
    ["Flame Orb", "Battle", "PVP Prize Shop", "800", "PVP Tokens"],
    ["Hawlucha", "Pokemon", "PVP Prize Shop", "750", "PVP Tokens"],
    ["Weakness Policy", "Battle", "PVP Prize Shop", "600", "PVP Tokens"],
    ["White Herb", "Battle", "PVP Prize Shop", "500", "PVP Tokens"],
    ["DamRock", "Battle", "PVP Prize Shop", "500", "PVP Tokens"],
    ["Heat Rock", "Battle", "PVP Prize Shop", "400", "PVP Tokens"],
    ["Darumaka", "Pokemon", "PVP Prize Shop", "400", "PVP Tokens"],
    ["Smooth Rock", "Battle", "PVP Prize Shop", "300", "PVP Tokens"],
    ["Mienfoo", "Pokemon", "PVP Prize Shop", "250", "PVP Tokens"],
    ["Icy Rock", "Evolution / Form", "PVP Prize Shop", "200", "PVP Tokens"],
    ["Vullaby", "Pokemon", "PVP Prize Shop", "200", "PVP Tokens"],
    ["Throh", "Pokemon", "PVP Prize Shop", "100", "PVP Tokens"],
    ["Sawk", "Pokemon", "PVP Prize Shop", "100", "PVP Tokens"],
    ["Fire Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Water Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Electric Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Grass Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Ice Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Fighting Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Poison Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Ground Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Flying Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Paychile Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Bug Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Rock Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Ghost Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Dragon Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Dark Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Steel Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Normal Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Fairy Gem", "Battle", "PVP Prize Shop", "75", "PVP Tokens"],
    ["Landorus", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Tornadus", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Thundurus", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Tapu Lele", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Tapu Koko", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Tapu Bulu", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Tapu Fini", "Pokemon", "Battle Queue Prize Shop", "7,000", "Competitive Points"],
    ["Zeraora", "Pokemon", "Battle Queue Prize Shop", "5,000", "Competitive Points"],
    ["Terrakion", "Pokemon", "Battle Queue Prize Shop", "5,000", "Competitive Points"],
    ["Hoopa", "Pokemon", "Battle Queue Prize Shop", "5,000", "Competitive Points"],
    ["Victini", "Pokemon", "Battle Queue Prize Shop", "3,500", "Competitive Points"],
    ["Thundurus Mount", "Decoration / Mount", "Battle Queue Prize Shop", "3,000", "Competitive Points"],
    ["Medichamite", "Evolution / Form", "Battle Queue Prize Shop", "2,500", "Competitive Points"],
    ["Charizardite X", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Charizardite Y", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Blastoisinite", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Venusaurite", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Blazikenite", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Sceptilite", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Swampertite", "Evolution / Form", "Battle Queue Prize Shop", "2,250", "Competitive Points"],
    ["Altarianite", "Evolution / Form", "Battle Queue Prize Shop", "1,750", "Competitive Points"],
    ["Pinsirite", "Evolution / Form", "Battle Queue Prize Shop", "1,750", "Competitive Points"],
    ["Slowbronite", "Evolution / Form", "Battle Queue Prize Shop", "1,750", "Competitive Points"],
    ["Nihilego", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Buzzwole", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Pheromosa", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Xurkitree", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Celesteela", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Kartana", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Guzzlord", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Poipole", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Stakataka", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Blacephalon", "Pokemon", "Battle Queue Prize Shop", "1,000", "Competitive Points"],
    ["Jangmo-o", "Pokemon", "Battle Queue Prize Shop", "750", "Competitive Points"],
    ["Air Balloon", "Battle", "Battle Queue Prize Shop", "600", "Competitive Points"],
    ["Foongus", "Pokemon", "Battle Queue Prize Shop", "600", "Competitive Points"],
    ["Mimikyu", "Pokemon", "Battle Queue Prize Shop", "550", "Competitive Points"],
    ["Red Card", "Battle", "Battle Queue Prize Shop", "500", "Competitive Points"],
    ["Pawniard", "Pokemon", "Battle Queue Prize Shop", "500", "Competitive Points"],
    ["Gligar", "Pokemon", "Battle Queue Prize Shop", "500", "Competitive Points"],
    ["Sneasel", "Pokemon", "Battle Queue Prize Shop", "450", "Competitive Points"],
    ["Skarmory", "Pokemon", "Battle Queue Prize Shop", "400", "Competitive Points"],
    ["Event Move Ticket", "Training / Grinding", "Battle Queue Prize Shop", "300", "Competitive Points"],
    ["Terrain Extender", "Battle", "Battle Queue Prize Shop", "300", "Competitive Points"],
    ["Hippopotas", "Pokemon", "Battle Queue Prize Shop", "300", "Competitive Points"],
    ["Light Clay", "Battle", "Battle Queue Prize Shop", "200", "Competitive Points"],
    ["Mental Herb", "Battle", "Battle Queue Prize Shop", "200", "Competitive Points"],
    ["Chansey", "Pokemon", "Battle Queue Prize Shop", "200", "Competitive Points"],
    ["Black Belt", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Black Glasses", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Charcoal", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Dragon Fang", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Hard Stone", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Magnet", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Miracle Seed", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Mystic Water", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Never Melt Ice", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Poison Barb", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["SharBeak", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Silk Scarf", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Silver Powder", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Soft Sand", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Spell Tag", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Twisted Spoon", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Iron Ball", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Grassy Seed", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Misty Seed", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Electric Seed", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Psychic Seed", "Battle", "Battle Queue Prize Shop", "150", "Competitive Points"],
    ["Growlithe", "Pokemon", "Battle Queue Prize Shop", "100", "Competitive Points"],
    ["Croagunk", "Pokemon", "Battle Queue Prize Shop", "80", "Competitive Points"],
    ["Shroomish", "Pokemon", "Battle Queue Prize Shop", "50", "Competitive Points"],
    ["Zygarde", "Pokemon", "Battle Tower Prize Shop", "40,000", "Tower Tokens"],
    ["Necrozma", "Pokemon", "Battle Tower Prize Shop", "35,000", "Tower Tokens"],
    ["Hoopa", "Pokemon", "Battle Tower Prize Shop", "32,500", "Tower Tokens"],
    ["Cobalion", "Pokemon", "Battle Tower Prize Shop", "30,000", "Tower Tokens"],
    ["Synchronize Stone", "Training / Grinding", "Battle Tower Prize Shop", "20,000", "Tower Tokens"],
    ["Alakazite", "Evolution / Form", "Battle Tower Prize Shop", "12,500", "Tower Tokens"],
    ["Absolite", "Evolution / Form", "Battle Tower Prize Shop", "10,000", "Tower Tokens"],
    ["Zygarde Mount", "Decoration / Mount", "Battle Tower Prize Shop", "10,000", "Tower Tokens"],
    ["Power Herb", "Battle", "Battle Tower Prize Shop", "7,500", "Tower Tokens"],
    ["Eviolite", "Battle", "Battle Tower Prize Shop", "6,000", "Tower Tokens"],
    ["Flame Orb", "Battle", "Battle Tower Prize Shop", "3,000", "Tower Tokens"],
    ["Toxic Orb", "Battle", "Battle Tower Prize Shop", "3,000", "Tower Tokens"],
    ["Bronzor", "Pokemon", "Battle Tower Prize Shop", "1,000", "Tower Tokens"],
    ["Spritzee", "Pokemon", "Battle Tower Prize Shop", "600", "Tower Tokens"],
    ["Everstone", "Evolution / Form", "Battle Tower Prize Shop", "500", "Tower Tokens"],
    ["Skelp", "Pokemon", "Battle Tower Prize Shop", "350", "Tower Tokens"],
    ["Cleffa", "Pokemon", "Battle Tower Prize Shop", "300", "Tower Tokens"],
    ["Abra", "Pokemon", "Battle Tower Prize Shop", "200", "Tower Tokens"],
    ["Growlithe", "Pokemon", "Battle Tower Prize Shop", "50", "Tower Tokens"],
    ["Landorus", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Tornadus", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Thundurus", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Tapu Lele", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Tapu Kobe", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Tapu Bulu", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Tapu Fri", "Pokemon", "Shiny Orb Prize Shop", "400", "Shiny Orb"],
    ["Magearna", "Pokemon", "Shiny Orb Prize Shop", "250", "Shiny Orb"],
    ["Larvitar", "Pokemon", "Shiny Orb Prize Shop", "200", "Shiny Orb"],
    ["Charizardite X", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Charizardite Y", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Blastoisinite", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Venusaurite", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Blazikenite", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Sceptilite", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Swampertite", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["White DNA Splicer", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Black DNA Splicer", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["N-Lunarizer", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["N-Solarizer", "Evolution / Form", "Shiny Orb Prize Shop", "75", "Shiny Orb"],
    ["Reveal Glass", "Evolution / Form", "Shiny Orb Prize Shop", "50", "Shiny Orb"],
    ["Prison Bottle", "Evolution / Form", "Shiny Orb Prize Shop", "50", "Shiny Orb"],
    ["Gracidea", "Evolution / Form", "Shiny Orb Prize Shop", "30", "Shiny Orb"],
    ["Zygarde Cell", "Evolution / Form", "Shiny Orb Prize Shop", "30", "Shiny Orb"]    
];